### PR TITLE
rust: Update dependencies to support new mangling scheme

### PR DESCRIPTION
**Pull request by tesuji**
Hope this support demangle new mangling scheme: https://www.reddit.com/r/rust/comments/bvifst/psa_new_rust_symbol_mangling_is_now_in_nightly/

New update log:

```rust
% cargo update
    Updating crates.io index
    Updating aho-corasick v0.6.6 -> v0.7.3
    Updating lazy_static v1.0.2 -> v1.3.0
    Removing libc v0.2.42
    Updating memchr v2.0.1 -> v2.2.0
    Updating regex v0.2.11 -> v1.1.7
    Updating regex-syntax v0.5.6 -> v0.6.7
    Updating rustc-demangle v0.1.8 -> v0.1.15
    Updating thread_local v0.3.5 -> v0.3.6
    Updating ucd-util v0.1.1 -> v0.1.3
    Removing unreachable v1.0.0
    Updating utf8-ranges v1.0.0 -> v1.0.3
    Removing void v1.0.2
```

### CODE REVIEW

**Comment by tesuji** [comment]
Ping @mattgodbolt , did you forget to merge this before https://github.com/mattgodbolt/compiler-explorer/pull/1437 ?

**Comment by mattgodbolt** [comment]
Hi: I will merge and deploy this now. Thanks

**Comment by mattgodbolt** [comment]
Deployed: please let me know if this seems OK to you now!

**Comment by tesuji** [comment]
Thanks for this. It is working perfectly.

**Pull request merged**
